### ISSUE TITLE
Cython error when installing on Windows 10

### ISSUE THREAD

**Issue by sbutler44** [Badcat330/TigerHash#5]
I'm trying to install TigerHash with ` pip install tigerhash ` and I am recieving the following error:

`
Collecting TigerHash
  Using cached tigerhash-0.2.0.tar.gz (42 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Simon\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\Simon\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Simon\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Simon\AppData\Local\Temp\pip-build-env-wmvl34q5\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Simon\AppData\Local\Temp\pip-build-env-wmvl34q5\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\Simon\AppData\Local\Temp\pip-build-env-wmvl34q5\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
`

I have ` Cython==0.29.33 ` reported from ` pip freeze ` and am running Python 3.10.9 on Windows 10 x64.

Can you recommend a fix?

Cheers, Simon.

**Comment by Kumokage** [comment]
Hi, Simon.
I configured and tested installing pipeline only for Mac OS. Project isn't ready for windows installation. Hope It will come soon. 

For Windows you can download sources and build project by yourself. 

Thank you for your comment.
Regards, Alex

**Comment by sirenuf** [comment]
I am getting the same error on Windows 10 LTSC 21H2 with pip 25.1.1/python 3.13.
I tried running it in a WSL session of Debian 13.3 and got the same Cython error:

```bash
viktor@ltscdesk:~/python-tigerhash/bin$ source activate
(python-tigerhash) viktor@ltscdesk:~/python-tigerhash/bin$ pip install tigerhash
Collecting tigerhash
  Downloading tigerhash-0.2.0.tar.gz (42 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/home/viktor/python-tigerhash/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
          ~~~~^^
        File "/home/viktor/python-tigerhash/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/viktor/python-tigerhash/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-5tpugfdr/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-5tpugfdr/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-5tpugfdr/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 2, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(python-tigerhash) viktor@ltscdesk:~/python-tigerhash/bin$ cat /etc/debian_version
13.3
(python-tigerhash) viktor@ltscdesk:~/python-tigerhash/bin$ pip --version
pip 25.1.1 from /home/viktor/python-tigerhash/lib/python3.13/site-packages/pip (python 3.13)
```
